/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.BookController;
import javax.swing.table.TableModel;
import models.FileTableModel;

/**
 *
 * @author William Sanchez
 */
public class BookList extends javax.swing.JInternalFrame {
    BookController bc;
    /**
     * Creates new form BookList
     */
    public BookList() {
        initComponents();
        setController();
        booksTable.setModel(new FileTableModel().getModel());
    }
    public void setController(){
        bc = new BookController(this);
        openDirectoryButton.addActionListener(bc);
        this.newBookButton.addActionListener(bc);
        this.showBookButton.addActionListener(bc);
    }

    public void SetDirectory(String filePath){
        this.directoryTextField.setText(filePath);
    }
    public void setBookTableModel(TableModel model){
        booksTable.setModel(model);
    }
    
    public String getSelectedBookFile(){
        return (String) booksTable.getValueAt(booksTable.getSelectedRow(), 1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        openDirectoryButton = new javax.swing.JButton();
        newBookButton = new javax.swing.JButton();
        showBookButton = new javax.swing.JButton();
        directoryTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        openDirectoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/open.png"))); // NOI18N
        openDirectoryButton.setText("Directorio");
        openDirectoryButton.setToolTipText("Seleccionar directorio");
        openDirectoryButton.setActionCommand("directory");
        openDirectoryButton.setFocusable(false);
        openDirectoryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openDirectoryButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(openDirectoryButton);

        newBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/new.png"))); // NOI18N
        newBookButton.setText("Nuevo");
        newBookButton.setToolTipText("Nuevo libro");
        newBookButton.setActionCommand("new");
        newBookButton.setFocusable(false);
        newBookButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newBookButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newBookButton);

        showBookButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/notepad.png"))); // NOI18N
        showBookButton.setText("Ver");
        showBookButton.setActionCommand("show");
        showBookButton.setFocusable(false);
        showBookButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showBookButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(showBookButton);

        directoryTextField.setPreferredSize(new java.awt.Dimension(200, 24));
        jToolBar1.add(directoryTextField);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(booksTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable booksTable;
    private javax.swing.JTextField directoryTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton newBookButton;
    private javax.swing.JButton openDirectoryButton;
    private javax.swing.JButton showBookButton;
    // End of variables declaration//GEN-END:variables
}
