/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JFileChooser;

/**
 *
 * @author Docente
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenu = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        Option1CheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        Option2CheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        demosMenu = new javax.swing.JMenu();
        OptionPaneSettingsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setLabel("Archivo");

        openMenu.setLabel("Abrir");
        openMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOpenDialog(evt);
            }
        });
        fileMenu.add(openMenu);

        saveMenuItem.setText("Guardar");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        optionsMenu.setText("Opciones");

        Option1CheckBoxMenuItem.setText("Opción 1");
        optionsMenu.add(Option1CheckBoxMenuItem);

        Option2CheckBoxMenuItem.setSelected(true);
        Option2CheckBoxMenuItem.setText("Opción 2");
        optionsMenu.add(Option2CheckBoxMenuItem);

        fileMenu.add(optionsMenu);
        fileMenu.add(jSeparator1);

        closeMenu.setLabel("Salir");
        closeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuActionPerformed(evt);
            }
        });
        fileMenu.add(closeMenu);

        mainMenuBar.add(fileMenu);

        helpMenu.setLabel("Ayuda");
        mainMenuBar.add(helpMenu);

        demosMenu.setText("Demos");

        OptionPaneSettingsMenuItem.setText("JOptionPane - Opciones");
        OptionPaneSettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionPaneSettingsMenuItemActionPerformed(evt);
            }
        });
        demosMenu.add(OptionPaneSettingsMenuItem);

        mainMenuBar.add(demosMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeMenuActionPerformed

    private void showOpenDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOpenDialog
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
    }//GEN-LAST:event_showOpenDialog

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showSaveDialog(this);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void OptionPaneSettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionPaneSettingsMenuItemActionPerformed
        OptionPaneDemo op = new OptionPaneDemo(); 
        op.setVisible(true);
    }//GEN-LAST:event_OptionPaneSettingsMenuItemActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Option1CheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem Option2CheckBoxMenuItem;
    private javax.swing.JMenuItem OptionPaneSettingsMenuItem;
    private javax.swing.JMenuItem closeMenu;
    private javax.swing.JMenu demosMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem openMenu;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables
}
