/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;

/**
 *
 * @author Docente
 */
public class MainForm extends javax.swing.JFrame {
JDesktopPane desktop;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/resources/images/tile.png")).getImage());
        desktop = new JDesktopPane();
        setContentPane(desktop);
        SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss");
        timeLabel.setText(time.format(new Date()));
        desktop.add(this.jToolBar1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        timeLabel = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFileMenuItem = new javax.swing.JMenuItem();
        openMenu = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        optionsMenu = new javax.swing.JMenu();
        Option1CheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        Option2CheckBoxMenuItem = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMenu = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        demosMenu = new javax.swing.JMenu();
        OptionPaneSettingsMenuItem = new javax.swing.JMenuItem();
        bookMenuItem = new javax.swing.JMenuItem();
        listMenuItem = new javax.swing.JMenuItem();
        externalMenuItem = new javax.swing.JMenuItem();
        verifyId = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        timeLabel.setText("00:00");
        jToolBar1.add(timeLabel);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        fileMenu.setLabel("Archivo");

        newFileMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/new.gif"))); // NOI18N
        newFileMenuItem.setText("Nuevo");
        newFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newFileMenuItem);

        openMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/open.gif"))); // NOI18N
        openMenu.setLabel("Abrir");
        openMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOpenDialog(evt);
            }
        });
        fileMenu.add(openMenu);

        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save.gif"))); // NOI18N
        saveMenuItem.setText("Guardar");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        optionsMenu.setText("Opciones");

        Option1CheckBoxMenuItem.setText("Opción 1");
        optionsMenu.add(Option1CheckBoxMenuItem);

        Option2CheckBoxMenuItem.setSelected(true);
        Option2CheckBoxMenuItem.setText("Opción 2");
        optionsMenu.add(Option2CheckBoxMenuItem);

        fileMenu.add(optionsMenu);
        fileMenu.add(jSeparator1);

        closeMenu.setLabel("Salir");
        closeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuActionPerformed(evt);
            }
        });
        fileMenu.add(closeMenu);

        mainMenuBar.add(fileMenu);

        helpMenu.setLabel("Ayuda");
        mainMenuBar.add(helpMenu);

        demosMenu.setText("Demos");

        OptionPaneSettingsMenuItem.setText("JOptionPane - Opciones");
        OptionPaneSettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionPaneSettingsMenuItemActionPerformed(evt);
            }
        });
        demosMenu.add(OptionPaneSettingsMenuItem);

        bookMenuItem.setText("Libros");
        bookMenuItem.setActionCommand("books");
        bookMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookMenuItemActionPerformed(evt);
            }
        });
        demosMenu.add(bookMenuItem);

        listMenuItem.setText("Lista de libros");
        listMenuItem.setActionCommand("list");
        listMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listMenuItemActionPerformed(evt);
            }
        });
        demosMenu.add(listMenuItem);

        externalMenuItem.setText("Libreria externa");
        externalMenuItem.setToolTipText("");
        externalMenuItem.setActionCommand("externalLib");
        externalMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalMenuItemActionPerformed(evt);
            }
        });
        demosMenu.add(externalMenuItem);

        verifyId.setText("Validar cédula");
        verifyId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyIdActionPerformed(evt);
            }
        });
        demosMenu.add(verifyId);

        mainMenuBar.add(demosMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeMenuActionPerformed

    private void showOpenDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOpenDialog
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(this);
        Notepad n = new Notepad(fileChooser.getSelectedFile());
        showChild(n,true);
    }//GEN-LAST:event_showOpenDialog

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        try{
            JInternalFrame selectedFrame = desktop.getSelectedFrame();
            if(selectedFrame.getClass().getName().equals(Notepad.class.getName())){
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.showSaveDialog(this);
                ((Notepad)selectedFrame).save(fileChooser.getSelectedFile());
            }
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void OptionPaneSettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionPaneSettingsMenuItemActionPerformed
        OptionPaneDemo op = new OptionPaneDemo(); 
        op.setVisible(true);
    }//GEN-LAST:event_OptionPaneSettingsMenuItemActionPerformed

    private void newFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileMenuItemActionPerformed
        
        Notepad n = new Notepad();
        showChild(n,false);

    }//GEN-LAST:event_newFileMenuItemActionPerformed

    private void bookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookMenuItemActionPerformed
        BookForm b = new BookForm();
        showChild(b,false);
    }//GEN-LAST:event_bookMenuItemActionPerformed

    private void listMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listMenuItemActionPerformed
        BookList bl = new BookList();
        showChild(bl, true);
    }//GEN-LAST:event_listMenuItemActionPerformed

    private void externalMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalMenuItemActionPerformed
        TestForm t = new TestForm();
        showChild(t,false);
    }//GEN-LAST:event_externalMenuItemActionPerformed

    private void verifyIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyIdActionPerformed
         ValidateIdForm v = new ValidateIdForm();
        showChild(v,false);
    }//GEN-LAST:event_verifyIdActionPerformed

    private void showChild(javax.swing.JInternalFrame frame, boolean maximizeForm){
        desktop.add(frame);
        frame.setLocation(0,0);
        frame.setVisible(true);
        if (maximizeForm)
            desktop.getDesktopManager().maximizeFrame(frame);  
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Option1CheckBoxMenuItem;
    private javax.swing.JCheckBoxMenuItem Option2CheckBoxMenuItem;
    private javax.swing.JMenuItem OptionPaneSettingsMenuItem;
    private javax.swing.JMenuItem bookMenuItem;
    private javax.swing.JMenuItem closeMenu;
    private javax.swing.JMenu demosMenu;
    private javax.swing.JMenuItem externalMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem listMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem newFileMenuItem;
    private javax.swing.JMenuItem openMenu;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JMenuItem verifyId;
    // End of variables declaration//GEN-END:variables
}
